import { palette, paletteNames } from './palette';
import { commonDevicePixelRatios, pixelUnit, UI_FONT_ART_PX } from './pixel';
import { semanticTokens, shadowInkPercent, themeTokens, type ThemeName } from './themes';

const HEADER =
  '/* Generated by scripts/build-tokens.ts from src/design. Do not edit: run `pnpm tokens`. */';

function round(value: number): string {
  return String(Number(value.toFixed(6)));
}

function themeDeclarations(theme: ThemeName, indent: string): string {
  const lines = semanticTokens.map(
    (token) => `${indent}--${token}: var(--c-${themeTokens[theme][token]});`,
  );
  lines.push(
    `${indent}--shadow: color-mix(in oklab, var(--c-ink) ${shadowInkPercent[theme]}%, transparent);`,
    `${indent}color-scheme: ${theme};`,
  );
  return lines.join('\n');
}

function unitMediaQueries(): string {
  const blocks: string[] = [];
  commonDevicePixelRatios.forEach((dpr, index) => {
    if (index === 0) return;
    const previous = commonDevicePixelRatios[index - 1] ?? dpr;
    const threshold = round((previous + dpr) / 2);
    blocks.push(
      `@media (min-resolution: ${threshold}dppx) {\n  :root {\n    --u: ${round(pixelUnit(dpr))}px;\n  }\n}`,
    );
  });
  return blocks.join('\n\n');
}

/** Renders src/styles/tokens.css. Pure, so tests can check the committed file is current. */
export function renderTokensCss(): string {
  const raw = paletteNames.map((name) => `  --c-${name}: ${palette[name]};`).join('\n');
  return `${HEADER}

:root {
${raw}

  /* One art pixel in CSS px; refined at runtime by the OS from the exact devicePixelRatio. */
  --u: ${round(pixelUnit(1))}px;
  --ui-font-size: calc(var(--u) * ${UI_FONT_ART_PX});
}

${unitMediaQueries()}

:root,
:root[data-theme='light'] {
${themeDeclarations('light', '  ')}
}

:root[data-theme='dark'] {
${themeDeclarations('dark', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${themeDeclarations('dark', '    ')}
  }
}
`;
}
